version: '3'

services:
  web:
    build: ./docker
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
